# Generated by Django 5.2.4 on 2025-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
                ('sin', models.IntegerField()),
                ('jira', models.IntegerField()),
                ('estado', models.CharField(choices=[('en_gestion', 'En Gestión'), ('autorizado', 'Autorizado'), ('finalizado', 'Finalizado')], default='en_gestion', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
