# Generated by Django 5.2.4 on 2025-08-08 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='autorizador1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='autorizador2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='autorizador3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='autorizador4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='fecha_pap',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='nombre_jira',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
